### ISSUE TITLE
public/assets is not in gitignore

### ISSUE THREAD

**Issue by gabiudrescu** [Monofony/Monofony#155]
**Description**  
The folder public/assets is not in gitignore

**Steps to reproduce**  
create a new project
run `yarn build` instead of `yarn dev` 
git commit -m "first commit"

observe public/assets is being committed, although it shouldn't. 

**Possible Solution**  
add public/assets to gitignore

**Comment by gabiudrescu** [comment]
this could be an issue of the monofony/skeleton or flex recipe, because Monofony/Monofony has the complete gitignore file.

**Comment by loic425** [comment]
@gabiudrescu You're right, I've seen this issue already, but I forgot to open an issue. This is a recipe error on monofony/core-bundle.

**Comment by loic425** [comment]
It's fixed now, thanks @gabiudrescu 🎉
