### ISSUE TITLE
Reference commit is gone

### ISSUE THREAD

**Issue by Shamanee** [Monofony/Monofony#222]
**Monofony version affected**: 0.2.3 & 0.3.2

**Description** 
I'm using the monofony bundle on a project that (I created july 2020) and since this friday (23/10), i have an error when using composer install. 
It fails to install `monofony/core (v0.2.3)`. It tries to dowload monofony/core from dist but the [link](https://codeload.github.com/Monofony/Core/legacy.zip/70778ec872c416cdbb7ef7debcd6e57bc920a2d5) leads to a 404 error. Then it tries to clone the commit, but the reference is gone (70778ec872c416cdbb7ef7debcd6e57bc920a2d5). Then I have a RuntimeException : 
> fatal: reference is not a tree: 70778ec872c416cdbb7ef7debcd6e57bc920a2d5

It does the same when I try to install a new project using the command `composer create-project monofony/skeleton acme` but this time, the commit reference is not the same ([link to the dist](https://codeload.github.com/Monofony/Core/legacy.zip/f407dea88750df7c7711348511d240b77bb161ca)): 
> fatal: reference is not a tree: f407dea88750df7c7711348511d240b77bb161ca

**Steps to reproduce**  
Install a new monofony project using the command `composer create-project monofony/skeleton acme`

**Comment by loic425** [comment]
@Shamanee I am sorry for this error. I am investigated on that error. I droped and recreated this package but that was not the right solution. 
I think you can execute this following command to fix that.
`composer update monofony/core`

**Comment by Shamanee** [comment]
Unfortunately, the update does not work. It still does the same error from the same reference. 

It also does not work when I try to install a new project with `composer create-project monofony/skeleton acme`, and I can not `composer update` here.

**Comment by loic425** [comment]
@Shamanee 
When I run 
```
export SYMFONY_ENDPOINT=https://flex.symfony.com/r/github.com/symfony/recipes-contrib/871
composer create-project monofony/skeleton acme
```
this works perfectly... 

Can you have a look where is the reference "70778ec872c416cdbb7ef7debcd6e57bc920a2d5" on your project. Is it on symfony.lock or on composer.lock?

**Comment by loic425** [comment]
@Shamanee Excuse me, I just reproduced after clearing composer cache (composer clearcache)
I'm gonna make a new version of the Skeleton on 0.3. And I'm searching to fix the error on an existing project.

**Comment by loic425** [comment]
@Shamanee I just found the problem. I just have to re-execute the repositories' split on each tags to recreate missing tags on Packagist. I just re-created v0.3.2 and v0.2.3 but I have to do that for all existing tags of this package.

**Comment by loic425** [comment]
@Shamanee composer install should resolve the problem for you.
The composer-create command is now ok without any new release.

**Comment by loic425** [comment]
@Shamanee Is that now ok for you?

**Comment by Shamanee** [comment]
@loic425 Sorry for the late answer. Yes it does work perfectly fine. 
Thank you so much !
