### ISSUE TITLE
Is it compatible with Symfony 5.x?

### ISSUE THREAD

**Issue by MagePsycho** [Monofony/Monofony#293]
Hello Monofony Team,

First of thanks for the great starter package for Symfony. This has great potential to be a de-facto tool for starting any Symfony application.

Some of the key concerns:
* Is it compatible with Symfony 5.x?
* Instead of re-inventing the wheel for API, why not to include API-Platform?

**Comment by loic425** [comment]
Yes, it will be compatible with Symfony 5 next week. It's ready on master branch. 

Yes there is an api pack. It uses Api Platform and contains first full customisable endpoints.

**Comment by loic425** [comment]
@MagePsycho v0.5.0 is released and is compatible with Symfony 5.x 🎉 
You can use ApiPlatform with the monofony/api-pack and its setup is explained here:
https://github.com/Monofony/Monofony#api
